# version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: my-jenkins
    ports:
      - "8180:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped  # 자동 재시작 설정

volumes:
  jenkins_data:  # 볼륨 생성