jenkins:
  container_name: jenkins
  build:
    context: jenkins-dockerfile
    dockerfile: Dockerfile
  restart: unless-stopped
  user: root
  ports: 
    -"8180:8080"
    -"50000:50000"
  volumes:
    - /var/jenkins_home:/var/jenkins_home