# version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    platform: linux/amd64  # ARM 호스트 대비
    container_name: jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped
    user: "1000"  # 권한 문제 방지를 위해 UID 지정

volumes:
  jenkins_home:  # 볼륨 생성